server:
    port: ${PORT:8083}

spring:
    application:
        name: hackaton-clientes-app
    datasource:
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_clientes}
        username: ${DATASOURCE_USERNAME:postgres}
        password: ${DATASOURCE_PASSWORD:teste123}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update  # Use 'update' to automatically update schema (create or update tables)
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC  # Set JDBC time zone to UTC (optional, adjust as needed)
        show-sql: false  # Enable SQL logging (optional, for debugging)
        generate-ddl: false  # Generate DDL from entity models (optional, for schema creation)
        open-in-view: false  # Disable Open Session in View (OSIV) to prevent lazy loading issues

eureka:
    client:
        service-url:
            defatulZone: ${eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka}
        fetch-registry: true
        register-with-eureka: true



openapi:
    service:
        title: hackaton-clientes-app-service doc
        version: 1.0.0
        url: http://localhost:8080 #api gateway url
springdoc:
    api-docs:
        path: /hackaton-clientes-app/v3/api-docs
    swagger-ui:
        path: /hackaton-clientes-app/swagger-ui.html